name: MC-MegaCore
version: 1.0-LEGACY
main: me.marco.core.McCore
commands:
  login:
    description: Login to the server
  register:
    description: Register an account
  setspawn:
    description: Set the server spawn
  spawn:
    description: Teleport to spawn
  premium:
    description: Toggle premium mode (auto-login)
  rank:
    description: Manage player ranks (MEMBER|VIP|ADMIN)
  vanish:
    description: Ocultarse de otros jugadores
